In [4]:
import numpy as np

In [5]:
a = np.arange(-15,15).reshape(5,6)**2
a

array([[225, 196, 169, 144, 121, 100],
       [ 81,  64,  49,  36,  25,  16],
       [  9,   4,   1,   0,   1,   4],
       [  9,  16,  25,  36,  49,  64],
       [ 81, 100, 121, 144, 169, 196]], dtype=int32)

In [7]:
#각 행의 최대값
a.max(axis=-1)

array([225,  81,   9,  64, 196], dtype=int32)

In [9]:
#각 열의 최소값 - 클래스넷 2번문제
a.min(axis=0)

array([9, 4, 1, 0, 1, 4], dtype=int32)

In [10]:
#각 열의 평균 - 슬라이드 2번문제
a.mean(axis=0)

array([81., 76., 73., 72., 73., 76.])

In [11]:
mask = np.min(a)
mask

0

In [12]:
np.where(a==mask)

(array([2], dtype=int64), array([3], dtype=int64))