In [1]:
import numpy as np

In [2]:
a= np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [7]:
blue = a[[0,1,2,3],[3,1,0,4]]
blue

array([ 3,  6, 10, 19])

In [10]:
mask = np.array( a%3==0,dtype = bool)
a[mask]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])