In [2]:
import numpy as np
a= np.arange(25).reshape(5,5)

In [3]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
blue = a[1::2,:3:2]
blue

array([[ 5,  7],
       [15, 17]])

In [16]:
red = a[:,1::2]
red

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [20]:
yellow =  a[4,:]
yellow

array([20, 21, 22, 23, 24])