## op.reduce( )
  add.reduce()
  
     배열에 있는 수,문자를 더한다
  logical_and.reduce()
  
     배열에 있는 논리가 모두 참이면 True, 아니면 False
  logical_or.reduce()
  
     배열에 있는 논리 중 하나라도 참이라면 True, 모두 거짓이면 False


- 숫자

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])

In [4]:
np.add.reduce(a)

10

- 문자

In [5]:
a = np.array(['ab','cd','ef'],dtype ='object')

In [6]:
np.add.reduce(a)

'abcdef'

- 논리

In [7]:
a=np.array([1,1,0,1])

In [8]:
np.logical_and.reduce(a)

False

In [9]:
np.logical_or.reduce(a)

True

- 각 행의 합

In [14]:
a= np.arange(3) + np.arange(0,40,10).reshape(-1,1)

In [15]:
np.add.reduce(a,1)

array([ 3, 33, 63, 93])

- 각 열의 합(이게 이차원 배열에서의 add.reduce() 기본값)

In [18]:
np.add.reduce(a)

array([60, 64, 68])

## op.accumulate ()
 add.accumulate()
     
     배열의 각각의 요소에다가 add.reduce()를 쓴 것
 logical_and.accumulate()
 
     배열의 각각의 요소에다가 logical_and.reduce()를 쓴것
    
 logical_or.accumulate()
 
     배열의 각각의 요소에다가 logical_or.reduce()를 쓴 것

- 숫자

In [19]:
a = np.array([1,2,3,4])

In [20]:
np.add.accumulate(a)

array([ 1,  3,  6, 10], dtype=int32)

- 문자

In [21]:
a = np.array(['ab','cd','ef'],dtype='object')

In [22]:
np.add.accumulate(a)

array(['ab', 'abcd', 'abcdef'], dtype=object)

- 논리

In [23]:
a = np.array([1,1,0])

In [24]:
np.logical_and.accumulate(a)

array([ True,  True, False])

In [25]:
np.logical_or.accumulate(a)

array([ True,  True,  True])

## op.reduceat()
 add.reduceat(a, indices)
     
     a라는 배열의 indices 부분 add.reduce()
     그리고 indices 다음 부터 끝까지 add.reduce()

In [34]:
a = np.array([0,10,20,30,40,50])

In [35]:
indices = np.array([2,4])

In [36]:
np.add.reduceat(a,indices)

array([50, 90], dtype=int32)

## op.outer()
add.outer(a,b)
    
    행렬 덧셈 a+b이다
    만약 b+a라면 계산이 달라짐

In [37]:
a =np.array([1,2,3,4])
b = np.array([9,8,7])

In [39]:
np.add.outer(a,b)

array([[10,  9,  8],
       [11, 10,  9],
       [12, 11, 10],
       [13, 12, 11]])

In [40]:
np.add.outer(b,a)

array([[10, 11, 12, 13],
       [ 9, 10, 11, 12],
       [ 8,  9, 10, 11]])